-- Seed raw locations from Salesforce/Kaptio export

insert into public.locations_raw (
  country_code,
  country_name,
  region_name,
  city_name,
  latitude,
  longitude,
  timezone,
  is_primary_destination
) values
  ('AU', 'Australia', 'Oceania', 'Adelaide', -34.9285, 138.6007, 'Australia/Adelaide', true),
  ('AU', 'Australia', 'Oceania', 'Airlie Beach', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Albany', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Albury', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Alice Springs', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Apollo Bay', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Augusta', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Australia', null, null, null, true),
  ('AU', 'Australia', 'Global', 'Australia', null, null, null, true),
  ('AU', 'Australia', null, 'Australia', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Ayers Rock', -25.3444, 131.0369, 'Australia/Darwin', true),
  ('AU', 'Australia', 'Oceania', 'Ballina', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Barossa Valley', null, null, null, true),
  ('AU', 'Australia', null, 'Barossa Valley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Bathurst Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Beerwah', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Biboohra', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Bicheno', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Blue Mountains', -33.7, 150.3, 'Australia/Sydney', true),
  ('AU', 'Australia', 'Oceania', 'Brisbane', -27.4698, 153.0251, 'Australia/Brisbane', true),
  ('AU', 'Australia', null, 'Brisbane', -27.4698, 153.0251, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Global', 'Brisbane', -27.4698, 153.0251, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Broome', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Bundanoon', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Busselton', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Byron Bay', null, null, null, true),
  ('AU', 'Australia', null, 'Byron Bay', null, null, null, true),
  ('AU', 'Australia', 'Global', 'Byron Bay', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Cabarita Beach', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Cairns', -16.9186, 145.7781, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Global', 'Cairns', -16.9186, 145.7781, 'Australia/Brisbane', true),
  ('AU', 'Australia', null, 'Cairns', -16.9186, 145.7781, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Canberra', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Canungra', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Cape Jervis', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Cape Tribulation', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Clare Valley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Coffs Harbour', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Coles Bay', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Coober Pedy', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Cradle Mountain', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Crystalbrook', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Darwin', -12.4634, 130.8456, 'Australia/Darwin', true),
  ('AU', 'Australia', null, 'Darwin', -12.4634, 130.8456, 'Australia/Darwin', true),
  ('AU', 'Australia', 'Oceania', 'Daydream Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Daylesford', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Devonport', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Esperance', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Exmouth', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Fitzroy Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Flinders Ranges', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Fraser Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Fremantle', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Freycinet', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Geelong', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Geraldton', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Gladstone', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Gold Coast', -28.0167, 153.4, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Grampians National Park', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Grandchester', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Green Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Halls Gap', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Hamilton Island', -20.3481, 148.9522, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Hayman Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Heron Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Hervey Bay', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Hobart', -42.8821, 147.3272, 'Australia/Hobart', true),
  ('AU', 'Australia', 'Oceania', 'Hunter Valley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kakadu', -13, 132.5, 'Australia/Darwin', true),
  ('AU', 'Australia', 'Oceania', 'Kangaroo Island', -35.7752, 137.2142, 'Australia/Adelaide', true),
  ('AU', 'Australia', 'Global', 'Kangaroo Island', -35.7752, 137.2142, 'Australia/Adelaide', true),
  ('AU', 'Australia', 'Oceania', 'Katherine', null, null, null, true),
  ('AU', 'Australia', null, 'Kimberley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kimberley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kings Canyon', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kingscote', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kingscote Airport', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Kununurra', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Lady Elliot Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Lake St Clair', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Launceston', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Lizard Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Lord Howe Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Magnetic Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Margaret River', -33.9536, 115.0753, 'Australia/Perth', true),
  ('AU', 'Australia', 'Oceania', 'Maryvale', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'McLaren Vale', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Melbourne', -37.8136, 144.9631, 'Australia/Melbourne', true),
  ('AU', 'Australia', 'Oceania', 'Mildura', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Mission Beach', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Monkey Mia', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Moreton Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Mornington Peninsula', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Mossman', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Mount Gambier', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'New South Wales', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Newcastle', null, null, null, true),
  ('AU', 'Australia', null, 'Newcastle', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Noosa Heads', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Northern Beaches', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Northern Territory', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Orpheus Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Palm Cove', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Paringa', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Penola', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Perth', -31.9505, 115.8605, 'Australia/Perth', true),
  ('AU', 'Australia', 'Global', 'Perth', -31.9505, 115.8605, 'Australia/Perth', true),
  ('AU', 'Australia', 'Oceania', 'Phillip Island', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Port Campbell', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Port Douglas', -16.4833, 145.45, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Port Fairy', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Port Lincoln', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Port Macquarie', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Port Stephens', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Pretty Beach', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Proserpine Whitsunday Coast Airport', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Queensland', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Rainforest Resorts', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Renmark', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Rockhampton', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Smithton', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'South Australia', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'South Yarra', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Southern Cross', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Strahan', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Sunshine Coast', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Sydney', -33.8688, 151.2093, 'Australia/Sydney', true),
  ('AU', 'Australia', 'Global', 'Sydney', -33.8688, 151.2093, 'Australia/Sydney', true),
  ('AU', 'Australia', 'Oceania', 'Tasmania', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Thredbo', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Torquay', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Townsville', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Victoria', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Warrnambool', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Western Australia', null, null, null, true),
  ('AU', 'Australia', 'Global', 'Western Australia', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Whitsundays', -20.25, 148.95, 'Australia/Brisbane', true),
  ('AU', 'Australia', 'Oceania', 'Wilpena Pound', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Windsor', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Wolgan Valley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Wollongong', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'Yarra Valley', null, null, null, true),
  ('AU', 'Australia', 'Oceania', 'naracoorte', null, null, null, true),
  ('BT', 'Bhutan', 'Asia', 'Bhutan', null, null, null, false),
  ('BT', 'Bhutan', 'Asia', 'Paro', null, null, null, false),
  ('BW', 'Botswana', 'Africa', 'Botswana', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Central Kalahari Game Reserve', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Chobe National Park', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Gaborone', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Kasane', -17.8167, 25.15, 'Africa/Gaborone', true),
  ('BW', 'Botswana', 'Africa', 'Linyanti Wildlife Reserve', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Livingstone', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Makgadikgadi Pans National Park', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Maun', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Moremi Game Reserve', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Okavango Delta', -19.3, 22.9, 'Africa/Gaborone', true),
  ('BW', 'Botswana', 'Africa', 'Selinda Reserve', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'South Luangwa National Park', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Tuli Game Reserve', null, null, null, true),
  ('BW', 'Botswana', 'Africa', 'Victoria Falls Town', null, null, null, true),
  ('KH', 'Cambodia', 'Asia', 'Cambodia', null, null, null, false),
  ('KH', 'Cambodia', 'Asia', 'Phnom Penh', null, null, null, false),
  ('KH', 'Cambodia', 'Asia', 'Siem Reap', null, null, null, false),
  ('CA', 'Canada', 'North America', 'Canada', null, null, null, false),
  ('CA', 'Canada', 'Europe', 'Toronto', null, null, null, false),
  ('CN', 'China', 'Asia', 'Beijing', null, null, null, false),
  ('CN', 'China', 'Asia', 'Chengdu', null, null, null, false),
  ('CN', 'China', 'Asia', 'China', null, null, null, false),
  ('CN', 'China', 'Asia', 'Shanghai', null, null, null, false),
  ('CN', 'China', 'Asia', 'Tibet', null, null, null, false),
  ('CN', 'China', 'Asia', 'Yichang', null, null, null, false),
  ('CK', 'Cook Islands', 'Oceania', 'Aitutaki', null, null, null, false),
  ('CK', 'Cook Islands', 'Oceania', 'Cook Islands', null, null, null, false),
  ('CK', 'Cook Islands', 'Oceania', 'Rarotonga', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Abu Simbel', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Alexandria', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Aswan', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Cairo', null, null, null, false),
  ('EG', 'Egypt', null, 'Cairo', null, null, null, false),
  ('EG', 'Egypt', 'Global', 'Egypt', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Egypt', null, null, null, false),
  ('EG', 'Egypt', null, 'Egypt', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Giza', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Hurghada', null, null, null, false),
  ('EG', 'Egypt', null, 'Hurghada', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Luxor', null, null, null, false),
  ('EG', 'Egypt', null, 'Luxor', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Nairobi', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'Sharm El Sheikh', null, null, null, false),
  ('EG', 'Egypt', null, 'Sharm El Sheikh', null, null, null, false),
  ('EG', 'Egypt', 'Africa', 'United States of America', null, null, null, false),
  ('FJ', 'Fiji', 'Oceania', 'Fiji', null, null, null, false),
  ('FJ', 'Fiji', null, 'Fiji', null, null, null, false),
  ('FJ', 'Fiji', 'Oceania', 'Nadi', -17.7765, 177.4356, 'Pacific/Fiji', false),
  ('FJ', 'Fiji', 'Oceania', 'Viti Levu', null, null, null, false),
  ('FJ', 'Fiji', 'Oceania', 'Yasawa Islands', null, null, null, false),
  ('FI', 'Finland', 'Europe', 'Finland', null, null, null, false),
  ('FI', 'Finland', 'Europe', 'Sweden', null, null, null, false),
  ('FR', 'France', 'Europe', 'France', null, null, null, false),
  ('FR', 'France', null, 'France', null, null, null, false),
  ('FR', 'France', 'Europe', 'Monaco', null, null, null, false),
  ('FR', 'France', null, 'Paris', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Bora Bora', -16.5004, -151.7415, 'Pacific/Tahiti', false),
  ('PF', 'French Polynesia', 'Oceania', 'French Polynesia', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Hiva Oa', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Huahine', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Moorea', -17.5333, -149.8333, 'Pacific/Tahiti', false),
  ('PF', 'French Polynesia', 'Oceania', 'Nuku Hiva', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Raiatea', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Rangiroa', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Taha''a', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Tahiti', -17.6509, -149.426, 'Pacific/Tahiti', false),
  ('PF', 'French Polynesia', 'Oceania', 'Tetiaroa', null, null, null, false),
  ('PF', 'French Polynesia', 'Oceania', 'Tikehau', null, null, null, false),
  ('DE', 'Germany', 'Europe', 'Germany', null, null, null, false),
  ('GR', 'Greece', 'Europe', 'Greece', null, null, null, false),
  ('GR', 'Greece', null, 'Greece', null, null, null, false),
  ('HK', 'Hong Kong', 'Asia', 'Hong Kong', null, null, null, false),
  ('IS', 'Iceland', 'Europe', 'Iceland', null, null, null, false),
  ('IN', 'India', 'Asia', 'Agra', null, null, null, false),
  ('IN', 'India', 'India', 'Agra', null, null, null, false),
  ('IN', 'India', 'Asia', 'Aurangabad', null, null, null, false),
  ('IN', 'India', 'India', 'Aurangabad', null, null, null, false),
  ('IN', 'India', 'Asia', 'Bandhavgarh National Park', null, null, null, false),
  ('IN', 'India', 'Global', 'Bhavnagar', null, null, null, false),
  ('IN', 'India', 'India', 'Chennai', null, null, null, false),
  ('IN', 'India', 'India', 'India', null, null, null, false),
  ('IN', 'India', 'Global', 'India', null, null, null, false),
  ('IN', 'India', 'Asia', 'India', null, null, null, false),
  ('IN', 'India', 'India', 'Jaipur', null, null, null, false),
  ('IN', 'India', 'Global', 'Jaipur', null, null, null, false),
  ('IN', 'India', 'Asia', 'Jaipur', null, null, null, false),
  ('IN', 'India', 'India', 'Khajuraho', null, null, null, false),
  ('IN', 'India', 'India', 'Kochi', null, null, null, false),
  ('IN', 'India', 'Asia', 'Kochi', null, null, null, false),
  ('IN', 'India', 'Asia', 'Mumbai', null, null, null, false),
  ('IN', 'India', 'India', 'Mumbai', null, null, null, false),
  ('IN', 'India', 'Global', 'Mumbai', null, null, null, false),
  ('IN', 'India', 'India', 'Munnar', null, null, null, false),
  ('IN', 'India', 'Asia', 'New Delhi', null, null, null, false),
  ('IN', 'India', 'India', 'New Delhi', null, null, null, false),
  ('IN', 'India', 'India', 'Pondicherry', null, null, null, false),
  ('IN', 'India', 'India', 'Ranthambhore National Park', null, null, null, false),
  ('IN', 'India', 'Asia', 'Ranthambhore National Park', null, null, null, false),
  ('IN', 'India', 'Global', 'Udaipur', null, null, null, false),
  ('IN', 'India', 'India', 'Udaipur', null, null, null, false),
  ('IN', 'India', 'India', 'Varanasi', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Bali', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Denpasar', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Indonesia', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Jimbaran', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Labuan Bajo', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Lombok', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Nusa Dua', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Seminyak', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Ubud', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Uluwatu', null, null, null, false),
  ('ID', 'Indonesia', 'Asia', 'Yogyakarta', null, null, null, false),
  ('IE', 'Ireland', 'Europe', 'Dublin', null, null, null, false),
  ('IE', 'Ireland', 'Europe', 'Ireland', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Ben Gurion International Airport', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Dead Sea - Israel', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Haifa', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Israel', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Jerusalem', null, null, null, false),
  ('IL', 'Israel', 'Middle East', 'Tel Aviv', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Agrigento', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Bellagio', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Bologna', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Casole d’Elsa', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Cefalu', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Chianti', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Florence', null, null, null, false),
  ('IT', 'Italy', null, 'Florence', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Guarene', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Italy', null, null, null, false),
  ('IT', 'Italy', 'Global', 'Italy', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Lucca', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Milan', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Naples', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Padua', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Palazzetto', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Palermo', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Perugia', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Pienza', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Positano', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Rome', null, null, null, false),
  ('IT', 'Italy', null, 'Rome', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Sant''Agata sui Due Golfi', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Siracusa', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Taormina', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Trieste', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Venice', null, null, null, false),
  ('IT', 'Italy', null, 'Venice', null, null, null, false),
  ('IT', 'Italy', 'Europe', 'Vicenza', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Chiba', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Hakone', null, null, null, false),
  ('JP', 'Japan', 'Africa', 'Hakone', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Japan', null, null, null, false),
  ('JP', 'Japan', null, 'Japan', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Kanazawa', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Kyoto', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Nagano City', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Nagasaki', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Osaka', null, null, null, false),
  ('JP', 'Japan', 'Africa', 'Osaka', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Sapporo', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Takayama', null, null, null, false),
  ('JP', 'Japan', 'Asia', 'Tokyo', null, null, null, false),
  ('JP', 'Japan', 'Africa', 'Tokyo', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Amman', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Aqaba', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Dana Biosphere Reserve', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Dead Sea - Jordan', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Jordan', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Petra', null, null, null, false),
  ('JO', 'Jordan', 'Middle East', 'Wadi Rum Protected Area', null, null, null, false),
  ('JO', 'Jordan', null, 'Wadi Rum Protected Area', null, null, null, false),
  ('KE', 'Kenya', 'Africa', 'Aberdare National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Amboseli National Park', null, null, null, true),
  ('KE', 'Kenya', null, 'Amboseli National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Chyulu Hills National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Dar es Salaam', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Diani', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Greater Masai Mara', null, null, null, true),
  ('KE', 'Kenya', null, 'Greater Masai Mara', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Kenya', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Kigali', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Kilimanjaro', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Laikipia County', null, null, null, true),
  ('KE', 'Kenya', null, 'Laikipia County', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Lake Naivasha', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Lake Nakuru National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Lewa Wildlife Conservancy', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Meru National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Mombasa', -4.0435, 39.6682, 'Africa/Nairobi', true),
  ('KE', 'Kenya', 'Africa', 'Mount Kenya National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Nairobi', -1.2921, 36.8219, 'Africa/Nairobi', true),
  ('KE', 'Kenya', 'Africa', 'Naivasha', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Nanyuki', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Netherlands', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Samburu National Park', null, null, null, true),
  ('KE', 'Kenya', null, 'Samburu National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Shaba National Reserve', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Tsavo East National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Tsavo West National Park', null, null, null, true),
  ('KE', 'Kenya', null, 'Tsavo West National Park', null, null, null, true),
  ('KE', 'Kenya', 'Africa', 'Watamu Marine National Park', null, null, null, true),
  ('LA', 'Laos', 'Asia', 'Laos', null, null, null, false),
  ('LA', 'Laos', 'Asia', 'Luang Prabang', null, null, null, false),
  ('LA', 'Laos', 'Asia', 'Vientiane', null, null, null, false),
  ('MY', 'Malaysia', 'Asia', 'Malaysia', null, null, null, false),
  ('MV', 'Maldives', 'Asia', 'Maldives', null, null, null, false),
  ('MV', 'Maldives', 'Africa', 'Maldives Islands', null, null, null, false),
  ('MV', 'Maldives', 'Asia', 'Maldives Islands', null, null, null, false),
  ('MV', 'Maldives', 'Asia', 'Male', null, null, null, false),
  ('MV', 'Maldives', 'Africa', 'Male', null, null, null, false),
  ('MU', 'Mauritius', 'Africa', 'Balaclava', null, null, null, false),
  ('MU', 'Mauritius', 'Africa', 'Belle Mara', null, null, null, false),
  ('MU', 'Mauritius', 'Africa', 'Central Flacq', null, null, null, false),
  ('MU', 'Mauritius', 'Africa', 'Curepipe', null, null, null, false),
  ('MU', 'Mauritius', 'Africa', 'Mauritius', null, null, null, false),
  ('MU', 'Mauritius', null, 'Mauritius', null, null, null, false),
  ('MX', 'Mexico', 'North America', 'Mexico', null, null, null, false),
  ('MX', 'Mexico', 'North America', 'Mexico City', null, null, null, false),
  ('MX', 'Mexico', 'North America', 'Oaxaca', null, null, null, false),
  ('MC', 'Monaco', 'Europe', 'Monaco', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Agafay Desert', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Atlas Mountains', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Casablanca', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Chefchaouen', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Erfoud', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Fez', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Marrakech', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Merzouga', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Morocco', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Rabat', null, null, null, false),
  ('MA', 'Morocco', 'Africa', 'Skoura', null, null, null, false),
  ('MZ', 'Mozambique', 'Africa', 'Bazaruto Island', null, null, null, true),
  ('MZ', 'Mozambique', 'Africa', 'Benguerra Island', null, null, null, true),
  ('MZ', 'Mozambique', 'Africa', 'Inhambane', null, null, null, true),
  ('MZ', 'Mozambique', 'Africa', 'Mozambique', null, null, null, true),
  ('MZ', 'Mozambique', 'Africa', 'Vilanculos', null, null, null, true),
  ('MM', 'Myanmar', 'Asia', 'Bagan', null, null, null, false),
  ('MM', 'Myanmar', 'Asia', 'Inle Lake', null, null, null, false),
  ('MM', 'Myanmar', 'Asia', 'Mandalay', null, null, null, false),
  ('MM', 'Myanmar', 'Asia', 'Myanmar', null, null, null, false),
  ('MM', 'Myanmar', 'Asia', 'Yangon', null, null, null, false),
  ('NA', 'Namibia', 'Africa', 'Damaraland', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Etosha National Park', null, null, null, true),
  ('NA', 'Namibia', null, 'Etosha National Park', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Kaokoland', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Namib-Naukluft National Park', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Namibia', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Okonjima Nature Reserve', null, null, null, true),
  ('NA', 'Namibia', null, 'Okonjima Nature Reserve', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Skeleton Coast National Park', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Swakopmund', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Walvis Bay', null, null, null, true),
  ('NA', 'Namibia', 'Africa', 'Windhoek', -22.5609, 17.0658, 'Africa/Windhoek', true),
  ('NP', 'Nepal', 'Asia', 'Bhutan', null, null, null, false),
  ('NP', 'Nepal', 'Asia', 'Kathmandu', null, null, null, false),
  ('NP', 'Nepal', 'Asia', 'Nepal', null, null, null, false),
  ('NL', 'Netherlands', null, 'Netherlands', null, null, null, false),
  ('NL', 'Netherlands', 'Global', 'Netherlands', null, null, null, false),
  ('NL', 'Netherlands', 'North America', 'Netherlands', null, null, null, false),
  ('NZ', 'New Zealand', 'Oceania', 'Abel Tasman National Park', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Ahuriri Valley', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Akaroa', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Arthur''s Pass', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Auckland', -36.8485, 174.7633, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', null, 'Auckland', -36.8485, 174.7633, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Auckland District', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Bay of Islands', -35.2282, 174.0918, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Bay of Plenty', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Blenheim', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Bluff', null, null, null, true),
  ('NZ', 'New Zealand', null, 'Cairns', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Cambridge', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Canterbury', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Christchurch', -43.5321, 172.6362, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Coromandel', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Dunedin', -45.8788, 170.5028, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Fairlie', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Fiordland National Park', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Fox Glacier', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Franz Josef', -43.388, 170.183, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Glenorchy', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Great Barrier Island', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Greymouth', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hamilton', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hanmer Springs', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hauraki Gulf', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hawke''s Bay', null, null, null, true),
  ('NZ', 'New Zealand', null, 'Hawke''s Bay', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hikurangi', null, null, null, true),
  ('NZ', 'New Zealand', null, 'Hikurangi', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Hokitika', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Invercargill', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Kaikoura', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Kerikeri', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Lake Moeraki', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Lake Pearson', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Lake Pukaki', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Lake Tekapo', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Manapouri', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Manawatu-Whanganui', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Mangawhai', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Marlborough', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Marlborough Sound', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Martinborough', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Matamata', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Milford', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Mount Cook', -43.734, 170.0962, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Murchison', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Napier', -39.4928, 176.912, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Nelson', -41.2706, 173.284, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Nelson District', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'New Plymouth', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'New Zealand', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'North Island', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Northland', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Oamaru', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Omarama', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Otago', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Otorohanga', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Paihia', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Palmerston North', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Picton', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Punakaiki', null, null, null, true),
  ('NZ', 'New Zealand', null, 'Punakaiki', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Queenstown', -45.0312, 168.6626, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Rotorua', -38.1368, 176.2497, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Russell', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'South Island', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Southland', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Stewart Island', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Taihape', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Takaka', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Taranaki', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Taupo', -38.6857, 176.0702, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Tauranga', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Te Anau', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Te Arai', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Thames', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Tongariro', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Turangi', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Twizel', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Waiheke Island', null, null, null, true),
  ('NZ', 'New Zealand', null, 'Waiheke Island', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Waikato', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Waitomo', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Wanaka', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Wellington', -41.2865, 174.7762, 'Pacific/Auckland', true),
  ('NZ', 'New Zealand', 'Oceania', 'Wellington District', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'West Coast', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Westport', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Whakatane', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Whanganui', null, null, null, true),
  ('NZ', 'New Zealand', 'Oceania', 'Whangarei', null, null, null, true)
;

insert into public.locations_raw (
  country_code,
  country_name,
  region_name,
  city_name,
  latitude,
  longitude,
  timezone,
  is_primary_destination
) values
  ('NZ', 'New Zealand', 'Oceania', 'Whitianga', null, null, null, true),
  ('PG', 'Papua New Guinea', 'Oceania', 'Papua New Guinea', null, null, null, false),
  ('PT', 'Portugal', 'Europe', 'Algarve', null, null, null, false),
  ('PT', 'Portugal', 'Europe', 'Lisbon', null, null, null, false),
  ('PT', 'Portugal', 'Europe', 'Porto', null, null, null, false),
  ('PT', 'Portugal', 'Europe', 'Portugal', null, null, null, false),
  ('QA', 'Qatar', 'Middle East', 'Cape Town', null, null, null, false),
  ('QA', 'Qatar', 'Middle East', 'Doha', null, null, null, false),
  ('QA', 'Qatar', 'Africa', 'Kilimanjaro', null, null, null, false),
  ('QA', 'Qatar', 'Middle East', 'Qatar', null, null, null, false),
  ('RW', 'Rwanda', 'Africa', 'Akagera National Park', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Kigali', -1.9403, 29.8739, 'Africa/Kigali', true),
  ('RW', 'Rwanda', 'Global', 'Kigali', -1.9403, 29.8739, 'Africa/Kigali', true),
  ('RW', 'Rwanda', null, 'Kigali', -1.9403, 29.8739, 'Africa/Kigali', true),
  ('RW', 'Rwanda', 'Africa', 'Kilimanjaro', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Lake Kivu', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Nairobi', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Nyungwe Forest National Park', null, null, null, true),
  ('RW', 'Rwanda', null, 'Nyungwe Forest National Park', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Rwanda', null, null, null, true),
  ('RW', 'Rwanda', 'Global', 'Rwanda', null, null, null, true),
  ('RW', 'Rwanda', 'Africa', 'Volcanoes National Park', -1.4833, 29.5333, 'Africa/Kigali', true),
  ('RW', 'Rwanda', null, 'Volcanoes National Park', -1.4833, 29.5333, 'Africa/Kigali', true),
  ('SC', 'Seychelles', 'Africa', 'Desroches Island', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'Frégate Island', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'La Digue', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'Mahe', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'Praslin', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'Praslin Island', null, null, null, false),
  ('SC', 'Seychelles', 'Africa', 'Seychelles', null, null, null, false),
  ('SG', 'Singapore', 'Asia', 'Singapore', null, null, null, false),
  ('SG', 'Singapore', null, 'Singapore', null, null, null, false),
  ('ZA', 'South Africa', 'Africa', 'Addo Elephant National Park', null, null, null, true),
  ('ZA', 'South Africa', 'Global', 'Africa', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Africa', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Buffalo Range Airport', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Cape Town', -33.9249, 18.4241, 'Africa/Johannesburg', true),
  ('ZA', 'South Africa', null, 'Cape Town', -33.9249, 18.4241, 'Africa/Johannesburg', true),
  ('ZA', 'South Africa', 'Africa', 'Constantia', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Dar es Salaam', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'De Hoop Nature Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Drakensberg Mountain Area', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Durban', -29.8587, 31.0218, 'Africa/Johannesburg', true),
  ('ZA', 'South Africa', 'Africa', 'Eastern Cape Game Reserves', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Franschhoek', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'George', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Hazyview', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Hermanus', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Hluhluwe-iMfolozi Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Hoedspruit', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Johannesburg', -26.2041, 28.0473, 'Africa/Johannesburg', true),
  ('ZA', 'South Africa', 'Africa', 'Kapama Private Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Klaserie Private Nature Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Knysna', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Kruger Mpumalanga International Airport', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Kruger National Park', -24, 31.5, 'Africa/Johannesburg', true),
  ('ZA', 'South Africa', 'Africa', 'Madikwe Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', null, 'Madikwe Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Malilangwe Wildlife Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Manyeleti Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Mbombela', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Montagu', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Nairobi', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Oudtshoorn', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Overberg', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Paarl', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Phinda Private Game Reserve/Hluhluwe', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Pietermaritzburg', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Pilanesberg National Park', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Port Elizabeth', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Pretoria', null, null, null, true),
  ('ZA', 'South Africa', null, 'Pretoria', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Sabi Sands Game Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Skukuza', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Skukuza Airport', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'South Africa', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Soweto', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Stellenbosch', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Sun City', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Swakopmund', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Thornybush Nature Reserve', null, null, null, true),
  ('ZA', 'South Africa', null, 'Thornybush Nature Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Timbavati Private Nature Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Tswalu Kalahari Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Umhlanga', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Victoria Falls Town', null, null, null, true),
  ('ZA', 'South Africa', null, 'Waterberg Biosphere Reserve', null, null, null, true),
  ('ZA', 'South Africa', 'Africa', 'Waterberg Biosphere Reserve', null, null, null, true),
  ('KR', 'South Korea', 'Asia', 'South Korea', null, null, null, false),
  ('ES', 'Spain', 'Europe', 'Spain', null, null, null, false),
  ('LK', 'Sri Lanka', 'Asia', 'Sri Lanka', null, null, null, false),
  ('SE', 'Sweden', 'Europe', 'Sweden', null, null, null, false),
  ('CH', 'Switzerland', 'Europe', 'Switzerland', null, null, null, false),
  ('TW', 'Taiwan', 'Asia', 'Taiwan', null, null, null, false),
  ('TZ', 'Tanzania', 'Africa', 'Arusha', -3.3869, 36.683, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', null, 'Arusha', -3.3869, 36.683, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', 'Africa', 'Dar es Salaam', -6.7924, 39.2083, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', 'Africa', 'Gombe National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Grumeti Game Reserve', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Karatu', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Katavi National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Kigali', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Kilimanjaro', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Lake Manyara National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Mahale Mountains National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Nairobi', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Ngorongoro', -3.2, 35.5, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', null, 'Ngorongoro', -3.2, 35.5, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', 'Africa', 'Nyerere National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Ruaha National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Rubondo Island National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Rwanda', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Serengeti National Park', null, null, null, true),
  ('TZ', 'Tanzania', null, 'Serengeti National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Tanzania', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Tarangire National Park', null, null, null, true),
  ('TZ', 'Tanzania', 'Africa', 'Zanzibar', -6.1659, 39.2026, 'Africa/Dar_es_Salaam', true),
  ('TZ', 'Tanzania', 'Africa', 'Zanzibar Resort Area', null, null, null, true),
  ('TZ', 'Tanzania', null, 'Zanzibar Resort Area', null, null, null, true),
  ('TH', 'Thailand', 'Asia', 'Bangkok', null, null, null, false),
  ('TH', 'Thailand', null, 'Bangkok', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Chiang Mai', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Chiang Rai', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Hua Hin', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Koh Samui', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Krabi', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Phuket', null, null, null, false),
  ('TH', 'Thailand', 'Asia', 'Thailand', null, null, null, false),
  ('TO', 'Tonga', 'Oceania', 'Tonga', null, null, null, false),
  ('UG', 'Uganda', 'Africa', 'Bwindi Impenetrable Forest National Park', null, null, null, true),
  ('UG', 'Uganda', null, 'Bwindi Impenetrable Forest National Park', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Entebbe', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Kampala', 0.3476, 32.5825, 'Africa/Kampala', true),
  ('UG', 'Uganda', 'Africa', 'Kibale Forest National Park', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Kigali', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Lake Mburo National Park', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Mgahinga Gorilla National Park', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Murchison Falls National Park', null, null, null, true),
  ('UG', 'Uganda', 'Africa', 'Queen Elizabeth National Park', -0.2, 30, 'Africa/Kampala', true),
  ('UG', 'Uganda', 'Africa', 'Uganda', null, null, null, true),
  ('AE', 'United Arab Emirates', 'Middle East', 'Abu Dhabi City', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Abu Dhabi Desert Area', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Dubai', null, null, null, false),
  ('AE', 'United Arab Emirates', null, 'Dubai', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Dubai Desert Area', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Emirate of Abu Dhabi', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Emirate of Dubai', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'Jordan', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Africa', 'Nairobi', null, null, null, false),
  ('AE', 'United Arab Emirates', 'Middle East', 'United Arab Emirates', null, null, null, false),
  ('GB', 'United Kingdom', 'Europe', 'England', null, null, null, false),
  ('GB', 'United Kingdom', 'Europe', 'London', null, null, null, false),
  ('GB', 'United Kingdom', 'Europe', 'Northern Ireland', null, null, null, false),
  ('GB', 'United Kingdom', 'Europe', 'Scotland', null, null, null, false),
  ('GB', 'United Kingdom', 'Africa', 'United Kingdom', null, null, null, false),
  ('US', 'United States', 'Europe', 'Atlanta', null, null, null, false),
  ('US', 'United States', 'Africa', 'Doha', null, null, null, false),
  ('US', 'United States', 'Africa', 'Dubai', null, null, null, false),
  ('US', 'United States', 'Africa', 'England', null, null, null, false),
  ('US', 'United States', 'North America', 'Hawaii', null, null, null, false),
  ('US', 'United States', 'Africa', 'Kilimanjaro', null, null, null, false),
  ('US', 'United States', 'North America', 'Nairobi', null, null, null, false),
  ('US', 'United States', 'North America', 'United States of America', null, null, null, false),
  ('US', 'United States', 'Africa', 'United States of America', null, null, null, false),
  ('US', 'United States', 'Global', 'United States of America', null, null, null, false),
  ('US', 'United States', null, 'United States of America', null, null, null, false),
  ('VU', 'Vanuatu', 'Oceania', 'Vanuatu', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Dalat', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Ha Long Bay', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Hanoi', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Ho Chi Minh City', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Hoi An', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Hue', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Nui Chua National Park', null, null, null, false),
  ('VN', 'Vietnam', 'Asia', 'Vietnam', null, null, null, false),
  ('ZM', 'Zambia', 'Africa', 'Kafue National Park', null, null, null, true),
  ('ZM', 'Zambia', null, 'Kafue National Park', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Liuwa Plain National Park', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Livingstone', -17.8419, 25.8544, 'Africa/Lusaka', true),
  ('ZM', 'Zambia', null, 'Livingstone', -17.8419, 25.8544, 'Africa/Lusaka', true),
  ('ZM', 'Zambia', 'Africa', 'Lower Zambezi National Park', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Lusaka', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Mfuwe Airport', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Nairobi', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'South Luangwa National Park', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Victoria Falls Town', null, null, null, true),
  ('ZM', 'Zambia', 'Africa', 'Zambia', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Africa', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Chobe National Park', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Dar es Salaam', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Harare', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Hwange National Park', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Livingstone', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Malilangwe Wildlife Reserve', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Mana Pools National Park', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Victoria Falls International Airport', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Victoria Falls Town', null, null, null, true),
  ('ZW', 'Zimbabwe', null, 'Victoria Falls Town', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Global', 'Victoria Falls Town', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Zambezi National Park', null, null, null, true),
  ('ZW', 'Zimbabwe', 'Africa', 'Zimbabwe', null, null, null, true)
;
